"""empty message

Revision ID: 619e40c38e74
Revises: 
Create Date: 2023-09-05 10:59:02.681053

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '619e40c38e74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
