"""reverted

Revision ID: 8810534945fa
Revises: b059396fdf33
Create Date: 2023-09-15 14:44:03.600532

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8810534945fa'
down_revision = 'b059396fdf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('_user_plan_uc', type_='unique')
        batch_op.drop_constraint('saved_plans_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('plan_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('saved_plans_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint('_user_plan_uc', ['user_id', 'plan_name'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
