"""Split plan into 4 columns

Revision ID: 08f779ab139f
Revises: 960bd4400743
Create Date: 2023-09-13 16:58:03.771579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f779ab139f'
down_revision = '960bd4400743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_routine', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('workout_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('diet_summary', sa.Text(), nullable=True))
        batch_op.drop_column('fitness_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitness_plan', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('diet_summary')
        batch_op.drop_column('workout_summary')
        batch_op.drop_column('workout_routine')

    # ### end Alembic commands ###
