"""updated all instances of username to user_id

Revision ID: 4f73e323e39e
Revises: b176959ee1a0
Create Date: 2023-09-15 11:38:57.312460

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4f73e323e39e'
down_revision = 'b176959ee1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_saved_plans_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('saved_plans_username_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('saved_plans_username_fkey', 'users', ['username'], ['username'])
        batch_op.drop_index(batch_op.f('ix_saved_plans_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
