"""added plan name

Revision ID: 903732215251
Revises: 08f779ab139f
Create Date: 2023-09-14 16:43:21.867295

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '903732215251'
down_revision = '08f779ab139f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name', sa.String(length=255), nullable=False, server_default='Plan_1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.drop_column('plan_name')

    # ### end Alembic commands ###
