"""Initial migration

Revision ID: 99d1349bdfad
Revises: 
Create Date: 2023-09-28 15:33:33.638265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d1349bdfad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True, nullable=False),
        sa.Column('username', sa.String(255), unique=True, nullable=False, index=True),
        sa.Column('email', sa.String(255), unique=True, nullable=False, index=True),
        sa.Column('age', sa.Integer),
        sa.Column('sex', sa.String(255)),
        sa.Column('weight', sa.Float),
        sa.Column('feet', sa.Integer),
        sa.Column('inches', sa.Integer),
        sa.Column('goals', sa.String(255)),
        sa.Column('days_per_week', sa.Integer),
        sa.Column('dietary_restrictions', sa.String(255)),
        sa.Column('created_at', sa.DateTime, default=sa.func.current_timestamp()),
        sa.Column('password_hash', sa.String(128))
    )
    
    # Create saved_plans table
    op.create_table(
        'saved_plans',
        sa.Column('id', sa.Integer, primary_key=True, nullable=False),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id')),
        sa.Column('workout_routine', sa.Text),
        sa.Column('workout_summary', sa.Text),
        sa.Column('diet_plan', sa.Text),
        sa.Column('diet_summary', sa.Text),
        sa.Column('plan_name', sa.String(255)),
        sa.Column('created_at', sa.DateTime, default=sa.func.current_timestamp())
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop saved_plans table
    op.drop_table('saved_plans')
    
    # Drop users table
    op.drop_table('users')
    
    # ### end Alembic commands ###
