"""reverted changes

Revision ID: ad7a62367341
Revises: 4f73e323e39e
Create Date: 2023-09-15 13:32:51.353575

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ad7a62367341'
down_revision = '4f73e323e39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))
        batch_op.drop_index('ix_saved_plans_user_id')
        batch_op.drop_constraint('saved_plans_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username'], ['username'])
        batch_op.drop_column('plan_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('plan_name', sa.VARCHAR(length=255), server_default=sa.text("'Plan_1'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('saved_plans_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_index('ix_saved_plans_user_id', ['user_id'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
