"""added plan name

Revision ID: b059396fdf33
Revises: fcf0d621beac
Create Date: 2023-09-15 14:28:24.711173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b059396fdf33'
down_revision = 'fcf0d621beac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.drop_constraint('saved_plans_plan_name_key', type_='unique')
        batch_op.create_unique_constraint('_user_plan_uc', ['user_id', 'plan_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.drop_constraint('_user_plan_uc', type_='unique')
        batch_op.create_unique_constraint('saved_plans_plan_name_key', ['plan_name'])

    # ### end Alembic commands ###
