"""added plan name

Revision ID: fcf0d621beac
Revises: 6e5595b214d9
Create Date: 2023-09-15 14:07:23.551143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf0d621beac'
down_revision = '6e5595b214d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_name', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['plan_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('plan_name')

    # ### end Alembic commands ###
